<?php echo '<?xml version="1.0" encoding="utf-8"?>';?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1*.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>error</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta name="MobileOptimized" content="320"/>
        <meta name="format-detection" content="telephone=no">
        <style type="text/css">
body { text-align: center; background-color: #cceeff;}
.alert{
    padding: 5px;
    margin:5px;
    color: #C09853;
    text-shadow:0 1px 0 rgba(255,255,255,0.5);
    background-color: #FFFFCC;
    border: 1px solid #FBEED5;
    -webkit-border-radius:4px;
    -moz-border-radius:4px;
    border-radius: 4px;
}
.alert_success {
    color: #468847;
    background-color: #DFF0D8;
    border-color: #D6E9C6;
}
.alter_info{
    color: #3A87AD;
    background-color: #D9EDF7;
    border-color: #BCE8F1;
}
img { vertical-align:middle; border:0;}
.nav {text-align: left;}
a {text-decoration: none;}
     </style>
    </head>
    <body>
   
<style type="text/css">
.nav_tips{font-size: large;}
.nav_main{padding: 5px;}
.nav_main_desc{margin: 5px;}
.nav_main_title{font-size: 20px;font-weight: bold;margin: 5px;}
</style>
<div class="nav">
    <div>
        <div class="alert alert_error">
            <div class="nav_main_title">oops! Server is busy!</div>
            <div class="nav_main_desc">
                Our server is very busy now, Please try again for a few minutes.<br />
                Let's try one of the following remedies to get you back on track...<br />
                <?php if (isset($_SERVER['HTTP_REFERER'])){?>
                Revisit the <a href="<?php echo $_SERVER['HTTP_REFERER'];?>">previous page</a> <br />
                <?php }?>
            </div>
        </div>
    </div>
</div>
    </body>

</html>
