<?php use utils\Common;?>
<?php require Common::getRequirePath() . "/header.phtml"; ?>
<?php
if(false !== strpos($_SERVER['HTTP_HOST'], "sunyie"))
{
    echo "<h1><font color='red'>线上环境</font></h1>";
}
else
{
    echo "<h1>测试环境</h1>";
}
?>
<table>
<tr><td><a href='/test/appreg' target='right_frame'>app注册</a></td></tr>
<tr><td><a href='/test/machinereg' target='right_frame'>商品注册</a></td></tr>
<tr><td><a href='/test/appbind' target='right_frame'>app绑定商品</a></td></tr>
<tr><td><a href='/test/appunbind' target='right_frame'>app解绑商品</a></td></tr>
<tr><td><a href='/test/teapotactionlog' target='right_frame'>teapot发送使用记录</a></td></tr>
<tr><td><a href='/test/teapotgetactionloglist' target='right_frame'>获取teapot使用记录列表</a></td></tr>
<tr><td><a href='/test/teapotupdatestate' target='right_frame'>teapot发送当前状态</a></td></tr>
<tr><td><a href='/test/teapotrequest' target='right_frame'>商品获取任务(心跳)</a></td></tr>
<tr><td><a href='/test/teapotrequestresult' target='right_frame'>teapot上传执行结果</a></td></tr>
<tr><td><a href='/test/teapotgetstate' target='right_frame'>app获取teapot状态</a></td></tr>
<tr><td><a href='/test/teapotheat' target='right_frame'>App发送teapot加热命令</a></td></tr>
<tr><td><a href='/test/teapotcancelheat' target='right_frame'>App发送teapot取消加热命令</a></td></tr>
<tr><td><a href='/test/appgetmachinelist' target='right_frame'>app获取可管理的商品列表</a></td></tr>
<tr><td><a href='/test/appgetmachinenum' target='right_frame'>app获取可管理的商品数量</a></td></tr>
<tr><td><a href='/test/appdeletemachine' target='right_frame'>app删除商品绑定关系</a></td></tr>
<tr><td><a href='/test/appcheckversion' target='right_frame'>app检查版本更新</a></td></tr>
<tr><td><a href='/test/appfeedback' target='right_frame'>app意见反馈</a></td></tr>
<tr><td><a href='/test/appclearallrequest' target='right_frame'>app清除某商品的全部预约</a></td></tr>
<tr><td><a href='/test/teapotstopheat' target='right_frame'>app发送停止当前加热命令</a></td></tr>
<tr><td><a href='/test/teapotgetorderlist' target='right_frame'>app获取某商品的任务列表</a></td></tr>
<tr><td><a href='/test/appupdatelocation' target='right_frame'>app更新经纬度</a></td></tr>
<tr><td><a href='/test/appfeedbackdetail' target='right_frame'>app获取反馈详情</a></td></tr>
<tr><td><a href='/test/appaddmsg' target='right_frame'>机器发送运行消息给app</a></td></tr>
<tr><td><a href='/test/appgetmsglist' target='right_frame'>app获取运行信息</a></td></tr>
<tr><td><a href='/test/appgetmsgnum' target='right_frame'>app所有运行信息的总数</a></td></tr>
<tr><td><a href='/test/appgetunreadmsglist' target='right_frame'>app获取未读的运行信息</a></td></tr>
<tr><td><a href='/test/appgetunreadmsgnum' target='right_frame'>app未读的运行信息的总数</a></td></tr>
<tr><td><a href='/test/appupdatemsgstatus' target='right_frame'>app更新运行消息状态（设置已读）</a></td></tr>
<tr><td><a href='/test/appdeletemsg' target='right_frame'>app删除运行信息</a></td></tr>
<tr><td><a href='/test/teapotstat' target='right_frame'>获取teapot的使用统计信息</a></td></tr>
<tr><td><a href='/test/appgetnearmachine' target='right_frame'>app获取相同出口ip的商品</a></td></tr>
<tr><td><a href='/test/teapotruntime' target='right_frame'>商品加热时上行运行数据</a></td></tr>
<tr><td>【加湿器接口】</td></tr>
<tr><td><a href='/test/humidifieractionlog' target='right_frame'>humidifier发送使用记录</a></td></tr>
<tr><td><a href='/test/humidifiergetactionloglist' target='right_frame'>获取humidifier使用记录列表</a></td></tr>
<tr><td><a href='/test/humidifierupdatestate' target='right_frame'>humidifier发送当前状态</a></td></tr>
<tr><td><a href='/test/humidifiergetstate' target='right_frame'>app获取humidifier状态</a></td></tr>
<tr><td><a href='/test/humidifierstat' target='right_frame'>获取humidifier的使用统计信息</a></td></tr>
<tr><td><a href='/test/humidifierrequest' target='right_frame'>humidifier获取是否需要工作（心跳）</a></td></tr>
<tr><td><a href='/test/humidifierstart' target='right_frame'>app开启加湿</a></td></tr>
<tr><td><a href='/test/humidifierstop' target='right_frame'>app关闭加湿</a></td></tr>
<tr><td><a href='/test/humidifiersaveconfig' target='right_frame'>app上传用户自定义配置</a></td></tr>
<tr><td><a href='/test/humidifiergetconfig' target='right_frame'>app获取用户自定义配置</a></td></tr>
<tr><td><a href='/test/humidifierorder' target='right_frame'>app对加湿器新增预约</a></td></tr>
<tr><td><a href='/test/humidifiergetorderlist' target='right_frame'>app获取预约列表</a></td></tr>
<tr><td><a href='/test/humidifiergetorder' target='right_frame'>app获取预约详情</a></td></tr>
<tr><td><a href='/test/humidifiercancelorder' target='right_frame'>app取消预约</a></td></tr>
<tr><td>【灯接口】</td></tr>
<!--
<tr><td><a href='/test/lightactionlog' target='right_frame'>light发送使用记录</a></td></tr>
-->
<tr><td><a href='/test/lightgetactionloglist' target='right_frame'>获取light使用记录列表</a></td></tr>
<tr><td><a href='/test/lightupdatestate' target='right_frame'>light发送当前状态</a></td></tr>
<tr><td><a href='/test/lightgetstate' target='right_frame'>app获取light状态</a></td></tr>
<tr><td><a href='/test/lightstat' target='right_frame'>获取light的使用统计信息</a></td></tr>
<tr><td><a href='/test/lightrequest' target='right_frame'>light获取是否需要工作（心跳）</a></td></tr>
<tr><td><a href='/test/lightrequestcallback' target='right_frame'>light心跳回调</a></td></tr>
<tr><td><a href='/test/lightstart' target='right_frame'>app开启灯</a></td></tr>
<tr><td><a href='/test/lightstop' target='right_frame'>app关闭灯</a></td></tr>
<tr><td><a href='/test/lightsaveconfig' target='right_frame'>app上传用户自定义配置</a></td></tr>
<tr><td><a href='/test/lightgetconfig' target='right_frame'>app获取用户自定义配置</a></td></tr>
<tr><td><a href='/test/lightorder' target='right_frame'>app对灯新增预约</a></td></tr>
<tr><td><a href='/test/lightgetorderlist' target='right_frame'>app获取预约列表</a></td></tr>
<tr><td><a href='/test/lightgetorder' target='right_frame'>app获取预约详情</a></td></tr>
<tr><td><a href='/test/lightcancelorder' target='right_frame'>app取消预约</a></td></tr>
<tr><td>【路由器接口】</td></tr>
<tr><td><a href='/test/routerupdatelist' target='right_frame'>路由器更新电器列表</a></td></tr>
<tr><td><a href='/test/routerclearlist' target='right_frame'>路由器清除电器列表</a></td></tr>
<tr><td>【开关接口】</td></tr>
<tr><td><a href='/test/bindSwitch' target='right_frame'>建立开关和灯的绑定关系</a></td></tr>
<tr><td><a href='/test/lightlist' target='right_frame'>获取开关同一路由器下所有的灯</a></td></tr>
</table>

<?php require Common::getRequirePath() . "/footer.phtml"; ?>

