<?php use utils\Common;?>
<?php require Common::getRequirePath() . "/header.phtml"; ?>

<form action='/test/teapotactionlog' method='POST'>
<table style='width:100%;background:#ACC5E0;' cellpadding='4' cellspacing='1'>
<tr style='background:#ffffff;'><td colspan='2'>teapot发送使用记录</td></tr>
<?php
echo Common::testItem("appid", "appid");
echo Common::testItem("电器id", "machineid");
echo Common::testItem("operation", "operation");
echo Common::testItem("starttime", "starttime");
echo Common::testItem("endtime", "endtime");
echo Common::testItem("level", "level");
echo Common::testItem("temp", "temp");
echo Common::testItem("boil", "boil");
echo Common::testItem("purify", "purify");
echo Common::testItem("keepwarm", "keepwarm");
echo Common::testItem("energy", "energy");
?>
<table>
<center><input type='submit' value=' 确 定 '></center>
</form>

<?php
if("POST" == $_SERVER['REQUEST_METHOD'])
{
?>
<table style='width:100%;background:#ACC5E0;' cellpadding='4' cellspacing='1'>
<tr style='background:#ffffff;'><td>请求详情</td></tr>
<tr style='background:#ffffff;'><td><textarea style='width:100%;height:130px;'><?php echo $requestString;?></textarea></td></tr>
<table>
<table style='width:100%;background:#ACC5E0;' cellpadding='4' cellspacing='1'>
<tr style='background:#ffffff;'><td>请求返回的结果</td></tr>
<tr style='background:#ffffff;'><td><textarea style='width:100%;height:130px;'><?php echo $result;?></textarea></td></tr>
<table>
<table style='width:100%;background:#ACC5E0;' cellpadding='4' cellspacing='1'>
<tr style='background:#ffffff;'><td>请求返回的结果(json格式)</td></tr>
<tr style='background:#ffffff;'><td><textarea style='width:100%;height:130px;'>
<?php
if(false !== ($p = strpos($result, "{")))
{
    if(false !== ($p1 = strrpos($result, "}")))
    {
        $result = substr($result, $p, $p1 - $p + 1); 
        $jsonArray = json_decode($result, true);
        print_r($jsonArray);
    }
}
?>
</textarea></td></tr>
<table>

<?php
}
?>

<?php require Common::getRequirePath() . "/footer.phtml"; ?>
