<?php use utils\Common;?>
<?php require Common::getRequirePath() . "/header.phtml"; ?>
<?php
if($msg)
{
    echo "<div>".$msg."</div>";
}

?>

<form action='/admin/cleartestdata' method='post'>
<table style='width:100%;background:#ACC5E0;' cellpadding='4' cellspacing='1'>
<tr style='background:#ffffff;'><td>清除测试电器数据(删除使用记录和绑定信息,一行一个电器id)</td></tr>
<tr style='background:#ffffff;'><td><textarea name='content' style='width:100%;height:300px;'></textarea></td></tr>
</table>
<center><input type='submit' onclick="return confirm('确定删除?')" value=' 确定 '></center>
</form>

<?php require Common::getRequirePath() . "/footer.phtml"; ?>
