<?php use utils\Common;?>
<?php require Common::getRequirePath() . "/header.phtml"; ?>
<table>
<tr><td><?php echo $_SESSION['username'];?>&nbsp;&nbsp;<a href='/admin/modifypassword' target='right_frame'>修改密码</a>&nbsp;&nbsp;<a href='/admin/logout'>退出</a></td></tr>
<tr><td><a href='/admin/appmanage' target='right_frame'>app管理</a></td></tr>
<tr><td><a href='/admin/machinemanage' target='right_frame'>商品管理</a></td></tr>
<tr><td><a href='/admin/feedbackmanage' target='right_frame'>反馈管理</a></td></tr>
<tr><td><a href='/admin/appmap' target='right_frame'>APP地图</a></td></tr>
<tr><td><a href='/admin/machinemap' target='right_frame'>商品地图</a></td></tr>
<tr><td><a href='/admin/mapdemo' target='right_frame'>地图demo</a></td></tr>
<tr><td><a href='/admin/syncmapdata' target='right_frame'>同步商品坐标</a></td></tr>
<tr><td><a href='/admin/cleartestdata' target='right_frame'>清除测试电器</a></td></tr>
</table>

<?php require Common::getRequirePath() . "/footer.phtml"; ?>

