<?php use utils\Common;?>
<?php require Common::getRequirePath() . "/header.phtml"; ?>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<center>
<?php
if($errMsg)
{
    echo "<font color='red'>".$errMsg."</font>";
}

if(false !== strpos($_SERVER['HTTP_HOST'], "sunyie"))
{
    $tip = "线上环境";
}
else
{
    $tip = "测试环境";
}
?>
<form action="/admin/login" method='post'>
<table style='width:300px;background:#ACC5E0;' cellpadding='4' cellspacing='1'>
<tr style='background:#ffffff;'><td colspan='2'>用户登陆(<?php echo $tip;?>)</td></tr>
<tr style='background:#ffffff;'><td style='width:90px;text-align:right;'>用户名:</td><td><input type='text' name='username'></td></tr>
<tr style='background:#ffffff;'><td style='width:90px;text-align:right;'>密码:</td><td><input type='password' name='password'></td></tr>
</table>
<input type='submit' value=' 登 陆 '>
</form></center>
<?php require Common::getRequirePath() . "/footer.phtml"; ?>
