<?php use utils\Common;?>
<?php require Common::getRequirePath() . "/header.phtml"; ?>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<center>
<?php
if($errMsg)
{
    echo "<font color='red'>".$errMsg."</font>";
}
?>
<form action="/admin/modifypassword" method='post'>
<table style='width:300px;background:#ACC5E0;' cellpadding='4' cellspacing='1'>
<tr style='background:#ffffff;'><td colspan='2'>修改密码</td></tr>
<tr style='background:#ffffff;'><td style='width:90px;text-align:right;'>旧密码:</td><td><input type='password' name='oldPassword'></td></tr>
<tr style='background:#ffffff;'><td style='width:90px;text-align:right;'>新密码:</td><td><input type='password' name='newPassword'></td></tr>
<tr style='background:#ffffff;'><td style='width:90px;text-align:right;'>确认密码:</td><td><input type='password' name='newPassword1'></td></tr>
</table>
<input type='submit' value=' 确 定 '>
</form></center>
<?php require Common::getRequirePath() . "/footer.phtml"; ?>
