<?php use utils\Common; ?>
<?php require Common::getRequirePath() . "/header.phtml"; ?>

<form action='<?php echo $data['url']; ?>' method='POST'>
    <table style='width:100%;background:#ACC5E0;' cellpadding='4' cellspacing='1'>
        <tr style='background:#ffffff;'>
            <td colspan='2'><?php echo $data['name']; ?></td>
        </tr>
        <?php
        echo "<tr style='background:#ffffff;'><td style='width:60px;'>url</td><td><input type='text' name='apiUrl' style='width:500px' value='".$data['targetUrl']."'></td></tr>";
        foreach ($data['param'] as $key => $val) {
            echo "<tr style='background:#ffffff;'><td style='width:60px;'>".$key."</td><td><input type='text' name='".$key."' style='width:500px' value='".$val."'></td></tr>";
        }
        ?>
    <table>
    <center><input type='submit' value=' 确 定 '></center>
</form>

<?php
if ("POST" == $_SERVER['REQUEST_METHOD'])
{
?>
<!--<table style='width:100%;background:#ACC5E0;' cellpadding='4' cellspacing='1'>
    <tr style='background:#ffffff;'>
        <td>请求详情</td>
    </tr>
    <tr style='background:#ffffff;'>
        <td><textarea style='width:100%;height:130px;'><?php /*echo $requestString; */?></textarea></td>
    </tr>
    <table>-->
        <!--<table style='width:100%;background:#ACC5E0;' cellpadding='4' cellspacing='1'>
            <tr style='background:#ffffff;'>
                <td>请求返回的结果</td>
            </tr>
            <tr style='background:#ffffff;'>
                <td><textarea style='width:100%;height:130px;'><?php /*echo $result; */?></textarea></td>
            </tr>
            <table>-->
                <table style='width:100%;background:#ACC5E0;' cellpadding='4' cellspacing='1'>
                    <tr style='background:#ffffff;'>
                        <td>请求返回的结果</td>
                    </tr>
                    <tr style='background:#ffffff;'>
                        <td>
                            <textarea style='width:100%;height:130px;'>
<?php
if (false !== ($p = strpos($result, "{"))) {
    if (false !== ($p1 = strrpos($result, "}"))) {
        $result = substr($result, $p, $p1 - $p + 1);
        $jsonArray = json_decode($result, true);
        //print_r($jsonArray);
    }
}
print_r($result);
?>
                            </textarea>
                        </td>
                    </tr>
                    <table>
<?php
}
?>

<?php require Common::getRequirePath() . "/footer.phtml"; ?>
