
<div id="footer-wrap">
        <div id="footer" class="content" style='text-align:center;'>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "http://connect.facebook.net/en/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-like" style='text-align:center;' data-width="210px" data-href="https://www.facebook.com/vidmate.official" data-layout="standard" data-action="like" data-show-faces="false" data-share="false"></div>
<br/>
vidmate.mobi &copy; 2014 
        </div>
    </div>
</div>
