<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $page_title;?></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=0" />
<meta name="format-detection" content="email=no" />
<meta name="format-detection" content="address=no" />
<meta name="format-detection" content="telephone=no" />
<meta name="description" content="<?php echo $page_description;?>" />
<meta name="keywords" content="<?php echo $page_keywords;?>" />
<meta name="copyright" content="vidmate.mobi" />
<link rel="stylesheet" href="/css/v3.css" type="text/css" />
<!--[if lte IE 6]>
<script type="text/javascript" src="/js/belatedPNG.js"></script>
<script type="text/javascript">
  var __IE6=true;
  DD_belatedPNG.fix('#logo a,#header-wrap,#menus a span,#slider .layout img,#more,#more span,#banner .title,#banner .download a,#play,#banner .app,#banner .social a,#banner .social a span');
</script>
<![endif]-->
<script type="text/javascript">
    var __FROM='';
</script>
</head>

