<div id="wrap">
<div id="header-fixed">
        <div id="header-wrap">
            <div id="header" class="content clear">
                <h1 id="logo">
                    <a href="/" title="vidmate.mobi" rel="home">vidmate.mobi</a>
                </h1>
                <div id="menus">
                    <a href="/" title="Home"><span class="cm">Home</span></a>
                    <a href="/features/" title="Features"><span class="cms">Features</span></a>
                    <a href="/help/" title="Help"><span class="cmbc">Help</span></a>
                    <a href="#" id="more"><span class="more">More</span></a>
                </div>
            </div>
        </div>
        <div id="menuMore">
            <div class="content">
                <ul class="clear">
                    <li class="primary">
                        <h2>Features</h2>
                        <a href="/features/"><span></span>Features</a>
                    </li>
                    <li>
                        <h2>About</h2>
                        <a href="https://www.facebook.com/vidmate.official"><span></span>Facebook</a><br/>
                        <a href="#"><span></span>Term of use</a><br/>
                        <a href="mailto:vidmatestudio@gmail.com"><span></span>Contact Us</a>
                    </li>
                </ul>
            </div>
        </div>
</div>

